apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
  labels:
    app: flask-app
spec:
  replicas: 4  
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: tr2452/my_todo_app:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: mongo-db-service  
        - name: MONGO_PORT
          value: "27017"
